trigger:
  branches:
    include:
      - main
pr: none

stages:
- stage: Build_Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  pool: 
    vmImage: ubuntu-2022
  jobs:
  - job: Deploy_UAT
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Build success
    
    - task: CmdLine@2
      inputs:
        script: |
          echo Deploy success



- stage: integration_test_cypress
  dependsOn: Build_Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  pool: 
    vmImage: ubuntu-2022
  jobs:
  - job: Increase_efficiency
    steps:
    - bash: npm install && npx playwright install
      displayName: "Installing Dependencies"

    - bash: cd playwright && npx playwright test testscenario/test-1.spec.ts --workers 2
      displayName: "Start test - Chrome"
      condition: succeededOrFailed()
    
    
    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        pathtoPublish: './playwright/playwright-report/index.html'
        artifactName: 'TestResults_chrome'
        publishLocation: 'Container'



      


